config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home' 

  get 'about',       to: 'pages#about'
  get 'home2',     to: 'pages#home'
  get 'gallery', to: 'pages#gallery'

  get 'design', to: 'pages#design'
  get 'contacts',     to: 'pages#contacts'

  resources :custom_cakes
  resources :contacts
  resources :subscribers, only: :create

  resources :cakes do
    collection do
      get 'doughs'
      get 'fillings'
      get 'decorations'
    end
  end

  resources :orders do
    resources :deliveries, only: [:new, :create, :confirmation]
    get 'confirmation', to: 'deliveries#confirmation'

    # ========================
    # tira tudo dos other e assign others para o index e o new/create do order_others
    resources :order_others
    member do
      get 'others'
      post 'assign_others'
    end


  end
end

app/models/decoration.rb
class Decoration < ApplicationRecord
  has_many :decoration_categories, dependent: :delete_all
  has_many :categories, through: :decoration_categories

  mount_uploader :photo, PhotoUploader

  has_many :cakes, dependent: :delete_all
  monetize :price_cents
end

app/controllers/decorations_controller.rb
class DecorationsController < ApplicationController
  before_action :set_cake, only: [:new, :create, :edit, :update]
  before_action :set_dough, only: [:new, :create, :edit, :update]
  before_action :set_filling, only: [:new, :create, :edit, :update]
  before_action :set_decoration, only: [:edit, :update]

  def index
  end

  def new
    @decorations = Decoration.all
  end

  def create
    if @cake.update(decoration_params)
      redirect_to order_path(@cake.order.id)
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def delete
  end

  private

  def set_cake
    @cake = Cake.find(params[:cake_id])
  end

  def set_dough
    @dough = Dough.find(params[:dough_id])
  end

  def set_filling
    @filling = Filling.find(params[:filling_id])
  end

  def decoration_params
    decoration_params = params.require(:cake).permit(:decoration, :size, :shape, :photo, :photo_cache)
    decoration_params[:decoration] = Decoration.find(decoration_params[:decoration])
    decoration_params
  end
end

app/views/decorations/_decoration.html.erb
<%= simple_form_for :cake, url: cake_dough_filling_decorations_path(@cake, @dough, @filling), method: :post do |f| %>
  <%= f.input :decoration, collection: @decorations, as: :radio_buttons, input_html: {placeholder: "Choose a fantastic decoration"} %>
  <%= f.input :size, collection: Cake::SIZES, as: :radio_buttons, input_html: {placeholder: "Choose your favourite size"} %>
  <%= f.input :shape, collection: Cake::SHAPES, as: :radio_buttons, input_html: {placeholder: "Choose a fantastic shape"} %>
  <%= f.submit "Go", class: "btn btn-lg btn-primary"%>
<% end %>

app/views/decorations/edit.html.erb
<%= render "decoration" %>

app/views/decorations/new.html.erb
<%= render "decoration" %>