config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home' 

  get 'about',       to: 'pages#about'
  get 'home2',     to: 'pages#home'
  get 'gallery', to: 'pages#gallery'

  get 'design', to: 'pages#design'
  get 'contacts',     to: 'pages#contacts'

  resources :custom_cakes
  resources :contacts
  resources :subscribers, only: :create

  resources :cakes do
    collection do
      get 'doughs'
      get 'fillings'
      get 'decorations'
    end
  end

  resources :orders do
    resources :deliveries, only: [:new, :create, :confirmation]
    get 'confirmation', to: 'deliveries#confirmation'

    # ========================
    # tira tudo dos other e assign others para o index e o new/create do order_others
    resources :order_others
    member do
      get 'others'
      post 'assign_others'
    end


  end
end

app/models/cake.rb
class Cake < ApplicationRecord
  belongs_to :decoration, optional: true
  belongs_to :dough
  belongs_to :filling, optional: true
  belongs_to :order
  monetize :price_cents

  SIZES = (1.5..5.0).step(0.5).map{|s| s} + (6.0..7.0).step(1.0).map{|s| s}
end

app/controllers/cakes_controller.rb
class CakesController < ApplicationController
  include ApplicationHelper
  skip_before_action :authenticate_user!
  before_action :set_cake, only: [:edit, :update, :destroy]

  def index
  end

  def new # dough
    @cake = Cake.new
    @doughs = Dough.all
    render :doughs
  end

  def show
  end

  def doughs
    @doughs = Dough.all
      respond_to do |format|
      format.html
      format.js
    end
  end

  def decorations
    @cake_params = cake_params
    @dough = Dough.find(cake_params[:dough]) unless cake_params[:dough].blank?
    @filling = Filling.find(cake_params[:filling]) unless cake_params[:filling].blank?
    @sizes = Cake::SIZES
    @decorations = Decoration.all
    @categories = Category.all
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    if session[:order_id].present? && Order.exists?(session[:order_id])
      @order = Order.find(session[:order_id])
    else
      session.delete(:order_id)
      @order = Order.new
    end

    @order.user = current_user unless current_user.blank?

    if @order.save
      session[:order_id] = @order.id
      if params[:cake].blank?
        flash[:alert] = "Seleccione uma opção"
        @cake = Cake.new
        @doughs = Dough.all
        render :doughs
      else
        @cake = Cake.new(convert_params(cake_params))
        @cake.price_cents = (@cake.dough.price_cents + @cake.decoration.price_cents) * @cake.size
        @cake.order = @order
        if @cake.save
          respond_to do |format|
            format.html { redirect_to order_order_others_path(@order)}
          end
        else
          respond_to do |format|
            format.html { render :doughs }
            format.js
          end
        end
      end
    else
      @cake = Cake.new
      @doughs = Dough.all
      render :doughs
    end
  end

  def edit
    if @cake.update(cake_params)
      redirect_to cake_dough_filling_path(@cake, @cake.dough)
    else
      render :edit
    end
  end

  def update
  end

  def destroy
    @order = current_order
    @cake.destroy
    respond_to do |format|
      format.html {redirect_to order_path(@order)}
      format.js
    end
  end

  private

  def cake_params
    params.require(:cake).permit(:dough, :filling, :decoration, :size, :age)
  end

  def convert_params(cake_params)
    result = {}
    result[:dough] = Dough.find(cake_params[:dough]) unless cake_params[:dough].blank?
    result[:filling] = Filling.find(cake_params[:filling]) unless cake_params[:filling].blank?
    result[:decoration] = Decoration.find(cake_params[:decoration]) unless cake_params[:decoration].blank?
    result[:age] = cake_params[:age].to_i unless cake_params[:age].blank?
    result[:size] = cake_params[:size].to_f unless cake_params[:size].blank?

    result
  end

  def set_cake
    @cake = Cake.find(params[:id])
  end
end

app/views/cakes/_decoration.html.erb
<%= simple_form_for :cake, url: cakes_path(@cake_params), method: :post do |f| %>
<div class="form-inner-wrapper container">
  <div class="form-scroll row row-height">
    <div class="col-md-9" style = "max-height: 100%;">
      <div class="row filters padded-1-bottom">
        <div class="col-sm-1 col-xs-6">
          <div class="navbar-ac-link category-title" id='all'>Tudo</div>
        </div>
        <% @categories.each do |category| %>
          <div class="col-sm-2 col-xs-6">
            <div class="navbar-ac-link category-title" id=<%= category.name.parameterize.underscore%> ><%= category.name %>
            </div>
          </div>
        <% end %>
      </div>
      <div id = "decoration-wrapper" class = "row-height" style = "max-height: 600px; overflow: scroll; padding-top: 20px;">

        <% @decorations.each do |decoration| %>

        <div class="col-md-4 card all <%= decoration.categories.map{ |c| c.name.parameterize.underscore }.join(" ") %> ">
          <div class= "img-decoration-wrapper" >
            <%= cl_image_tag decoration.photo %>
            <div class="flexbox-between" style = "margin-bottom: 1.1em;">
                <%= decoration.name %>
                <%= f.radio_button :decoration, decoration.id, id: "cake_decoration_#{decoration.id}", class: 'radio-button option-input radio'%>
            </div>
            <hr>
            <div class="row">
              <div class="col-md-9"><p style = "margin-bottom: 1.1em;"> + <span id= "decoration_price_<%= decoration.id %>" class = "price"><%= decoration.price %></span> €/Kg</p></div>

            </div>
            <div class="row">
              <div class="col-md-12">
                <p style = "margin-bottom: 1.1em;">A partir de <span id= "decoration_quant_<%= decoration.id %>"><%= decoration.minimum_size %></span> kg</p>
              </div>

            </div>
          </div>
        </div>

        <% end %>

      </div>
    </div>
    <div class="col-md-3">

      <p class = "navbar-ac-link">Peso</p>
      <%= f.input :size, collection: Cake::SIZES, label: false, prompt: "Kg" %>

      <p class = "navbar-ac-link">Mensagem</p>
      <%= f.input :message, as: :text, input_html: {placeholder: "Texto para bolo"}, label: false %>

      <p class = "navbar-ac-link">Idade</p>
      <%= f.input :age, input_html: {placeholder: "Idade para as velas"}, label: false %>
    </div>
  </div>
  <%= f.input :dough, as: :hidden, input_html: {value: @dough.id}%>
  <span id = "dough_price" class = "hidden"><%= @dough.price %></span>
  <%= f.input :filling, as: :hidden, input_html: {value: @filling.id}%>
  <%= f.submit "Proximo passo", class: "btn btn-lg btn-default", id: "step2"%>
</div>
<% end %>

app/views/cakes/_dough.html.erb
<%= simple_form_for :cake, url: decorations_cakes_path, method: :get do |f| %>
<div class="form-inner-wrapper container">
  <div class="form-scroll row row-height">
   <% @doughs.each do |dough| %>
   <div class="col-md-4 doughs card" id = "div_<%= dough.id %>">
    <div class = "img-dough-wrapper" >
      <div class="row flexbox">
        <%= cl_image_tag dough.photo %>
      </div>
      <div class="row dough-label" id = "dough_i_<%= dough.id %>" style = "max-width: 100%">
        <p><%= dough.name %></p>
      </div>
    </div>
    <hr>
    <div class="dough-radio radio-hide">
      <%= f.radio_button :dough, dough.id, input_html: { class: "radio-button"}%>
    </div>
    <div class="row fillings" style = "padding-top: 40px">
      <% dough.fillings.each do |filling| %>
      <div style = "padding-bottom: 1.1em; display: flex; justify-content: space-between; align-items: center">
          <%= filling.name %>
        <div id = "fil_dough_<%= dough.id %>" style = "margin-left: 10px;">
          <div class="radio option-input i-filling" id = "i_<%= filling.id %>"></div>
        </div>
        <div class="radio-hide">
          <%= f.radio_button :filling, filling.id, id: "cake_filling_#{filling.id}", class: 'radio-button'%>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  <% end %>

</div>
</div>

<div class="row">
  <%= f.submit "Próximo passo", class: "btn cta-btn cta-btn-blue cta-btn-small", id: "step1" %>
</div>
<% end %>

app/views/cakes/_filling.html.erb
<%= simple_form_for :cake, url: decorations_cakes_path(@cake_params), remote: true, method: :get do |f| %>
  <% @fillings.each do |filling| %>
  <div class="funkyradio">
  <div class="funkyradio-default">
    <%= f.radio_button :filling, filling.id %>
    <%= label :filling, filling.name %>
    </div>
    </div>
    <%= f.input :dough, as: :hidden, input_html: {value: @dough.id}%>
  <% end %>
  <div class="flexbox">
    <%= f.submit "Próximo passo", class: "btn cta-btn cta-btn-blue cta-btn-small text-center"%>
  </div>
<% end %>

app/views/cakes/decorations.html.erb
<div class="form-page" style = "padding-bottom: 100px; padding-top: 100px;">
  <div class="container">
    <h1 id = "step-title">Decoração e Peso</h1>
    <div id="progresstracker">
      <ul>
        <li id = "wiz-1" class = "complete" ><span>1</span></li>
        <li id = "wiz-2" class = "active complete" ><span>2</span></li>
        <li id = "wiz-3" ><span>3</span></li>
        <li id = "wiz-4"><span>4</span></li>
        <li id = "wiz-5"><span>5</span></li>
      </ul>
    </div>
    <div class="form-wrapper">
      <%= render "decoration" %>

      <div id = "down-nav">
        <div class = "down-nav-btn">
          <%= link_to session[:back_link], class: "navbar-ac-link" do %>
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 48 48" xml:space="preserve" width="48" height="48">
            <g class="nc-icon-wrapper">
              <path id = "path1-l" fill="#72C472" d="M24,1C11.31787,1,1,11.31787,1,24s10.31787,23,23,23s23-10.31787,23-23S36.68213,1,24,1z">
              </path>
              <path id = "path2-l" fill="#FFFFFF" d="M23,16c0-0.37598-0.21094-0.72021-0.54639-0.89111c-0.33496-0.16992-0.73682-0.13867-1.04199,0.08252l-11,8 C10.15332,23.37939,10,23.68018,10,24s0.15332,0.62061,0.41162,0.80859l11,8C21.58594,32.93555,21.79248,33,22,33 c0.15479,0,0.31055-0.03613,0.45361-0.10889C22.78906,32.72021,23,32.37598,23,32v-6h13c0.55228,0,1-0.44772,1-1v-2 c0-0.55228-0.44772-1-1-1H23V16z">
              </path>
            </g>
          </svg>
          <% end %>
        </div>
        <div class = "down-nav-btn" id="submit-btn">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 48 48" xml:space="preserve" width="48" height="48">
            <g class="nc-icon-wrapper">
              <path id = "path1-r" fill="#D4D4D4" d="M24,1C11.31787,1,1,11.31787,1,24s10.31787,23,23,23s23-10.31787,23-23S36.68213,1,24,1z">
              </path>
              <path id = "path2-r" fill="#FFFFFF" d="M37.58838,23.19141l-11-8c-0.30322-0.22119-0.70703-0.25244-1.04199-0.08252 C25.21094,15.27979,25,15.62402,25,16v6H12c-0.55229,0-1,0.44772-1,1v2c0,0.55228,0.44771,1,1,1h13v6 c0,0.37598,0.21094,0.72021,0.54639,0.89111C25.68945,32.96387,25.84521,33,26,33c0.20752,0,0.41406-0.06445,0.58838-0.19141l11-8 C37.84668,24.62061,38,24.31982,38,24S37.84668,23.37939,37.58838,23.19141z">
              </path>
            </g>
          </svg>
        </div>
        <div class = "down-nav-cart">
          <p> Total: <span id = "cart"></span></p>
        </div>
      </div>
    </div>
    <%= link_to design_path, class: "navbar-ac-link" do %>
    Não encontra o que quer?
    <% end %>
  </div>
</div>
</div>


<div class="modal fade" id="enlargeImageModal" tabindex="-1" role="dialog" aria-labelledby="enlargeImageModal" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
      </div>
      <div class="modal-body">
        <img src="" class="enlargeImageModalSource" style="width: 100%;">
      </div>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
<script>
  $(document).ready(function(){
    $("#step2").attr('class', 'hidden'); //hide submit button
    $(".radio-hide").attr('class', 'hidden'); //hide radio buttons
    $("#submit-btn").removeClass("hidden");
    //Add dough price to cart
    $("#cart").append("<%= @dough.price%>€/Kg");
    //Enlarge images
    $(function() {
      $('img').on('click', function() {
        $('.enlargeImageModalSource').attr('src', $(this).attr('src'));
        $('#enlargeImageModal').modal('show');
      });
    });

    //In mobile, fix navbar to the bottom of the screen
    if ($(window).width() <= 400) {
      $('#down-nav').css({
        position: "fixed", bottom: "0", right: "0", left: "0"
      });
      var bottomOfForm = $(".form-wrapper").offset().top;
      $(window).scroll(function() {
        if($(window).scrollTop() > bottomOfForm) { //scrolled past the other div?
          $('#down-nav').css({
        position: "absolute"}) //reached the desired point -- show div
        } else {
          $('#down-nav').css({
            position: "fixed", bottom: "0", right: "0", left: "0"
          })
        }
      });
    };

    //When the user selects a decoration
    $("*[id*=cake_decoration_]").on('click', function(event){
      //Get decoration id
      var decorationId = $(this).attr('id');
      var splitDec = decorationId.split("cake_decoration_");
      var decorationIdNum = Number(splitDec[1]);
      var quantity = Number($("#decoration_quant_" + decorationIdNum).html());
      //Get decoration price
      var decorationPrice = Number($("#decoration_price_" + decorationIdNum).text());
      //Check if the size is already selected
      if ($("#cake_size").val() != "" && $("#cake_size").val() != null) {
        //If yes
        //Check if the selected quantity is compatible with current decoration
        if ($("#cake_size").val() < quantity) {
          event.preventDefault();
          $("#pre-down-nav").notify("Esta decoração não está disponível para a quantidade seleccionada");
        } else {
           //Multiply dough's price and decoration's price by quantity
           $("#cart").empty();
           $("#cart").html(((Number($("#dough_price").html()) + decorationPrice) * $("#cake_size").val()).toFixed(2) + "€");
          //Change button color
          $('#path1-r').css({ fill: "#72C472" });
        }
      } else {
        //Make some sizes unvailable
        $('option').filter(function() {
          return $(this).val() < quantity;
        }).prop('disabled', true);
      //Make the others available
      $('option').filter(function() {
        return $(this).val() >= quantity;
      }).prop('disabled', false);

      //Add price to cart
      $("#cart").empty();
      $("#cart").html((decorationPrice + Number($("#dough_price").html())).toFixed(2) + "€/Kg");
    }
    $("#cake_size").change(function(e) {
      var minQuant = $(this).val();
      //Multiply dough's price by quantity
      $("#cart").html(Number($("#dough_price").html()) * minQuant + "€");
      $("*[id*=decoration_quant_]").filter(function(){
        return $(this).html() >= minQuant
      }).each(function(index) {
        $(this).closest(".card").find("input").prop("disabled");
      });
    })
  });

    //When the user selects a size
    $("#cake_size").click(function(e) {

      //Verify if the decoration is already selected
      if (($("*[id*=cake_decoration_]").is(":checked") == true)) {
        //If yes
        //Get the selected decoration id
        var decorationId = $("*[id*=cake_decoration_]:checked").attr("id");
        var splitDec = decorationId.split("cake_decoration_");
        var decorationIdNum = Number(splitDec[1]);
        var decorationPrice = Number($("#decoration_price_" + decorationIdNum).text());
        //When changing the quantity
        $("#cake_size").change(function(e) {
         var minQuant = $(this).val();
         if (minQuant != "" && minQuant !=null) {
          $("*[id*=decoration_quant_]").filter(function(){
            return $(this).html() >= minQuant
          }).each(function(index) {
            $(this).closest(".card").find("input").prop("disabled");
          });
          $("#cart").html(((Number($("#dough_price").html()) + decorationPrice) * minQuant).toFixed(2) + "€");

        //Change button color
        $('#path1-r').css({ fill: "#72C472" });
      }
    })
        //Make some sizes unvailable
        $("input[name='cake[decoration]']:checked");
      } else {
     //All sizes are available
     $("#cake_size").change(function(e) {
      var minQuant = $(this).val();
      //Multiply dough's price by quantity
      $("#cart").html((Number($("#dough_price").html()) * minQuant).toFixed(2) + "€");
      $("*[id*=decoration_quant_]").filter(function(){
        return $(this).html() >= minQuant
      }).each(function(index) {
        $(this).closest(".card").find("input").prop("disabled");
      });
    })
   }
 })


    $("#submit-btn").click(function(e){
      if (($("*[id*=cake_decoration_]").is(":checked") == true) && ($("#cake_size").val() != "" && $("#cake_size").val() !=null))
      {
       $("#step2").click();
     } else {
      $(this).notify("Seleccione uma decoração e um tamanho");
    }
  })
  })

  //Categories
  $("#all").click(function(e){
    $(this).addClass("active-category");
    $("*[id*=category_]").removeClass("active-category");
    $(".all").hide();
    $(".all").show();
  });

  const categories = <%= raw @categories.map{ |category| category.name.parameterize.underscore } %>

  categories.forEach(function(category) {
    $("#" + category).click(function(e){
      $(this).addClass("active-category");
      $("*[id*=category_]").not(this).removeClass("active-category");
      $("#all").removeClass("active-category");
      $(".all").hide();
      $("." + category).show();
    });
  });


</script>
<% end %>

app/views/cakes/doughs.html.erb
<!-- <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Open Modal</button> -->
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Instruções</h4>
      </div>
      <div class="modal-body">
        <div class = "modal-content-wrapper flexbox">
          <%= image_tag("time-3.svg") %>
          <p>Qualquer encomenda deve ser feita com pelo menos 48h de antecedência.</p>
        </div>
        <div class = "modal-content-wrapper flexbox">
          <%= image_tag("round-euro.svg") %>
          <p>O pagamento é feito no acto da entrega. Pode pagar em numerário ou multibanco. Todos os preços incluiem IVA.</p>
        </div>
        <div class = "modal-content-wrapper flexbox">
          <%= image_tag("delivery.svg") %>
          <p>Pode escolher receber a encomenda numa morada específica ou levanta-la na loja.</p>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
      </div>
    </div>

  </div>
</div>

<section class="form-page" style = "padding-bottom: 100px; padding-top: 100px;">
  <div class="container">
    <h1 id = "step-title">Massa e Recheio</h1>
    <div id="progresstracker">
      <ul>
        <li id = "wiz-1" class = "active complete" ><span>1</span></li>
        <li id = "wiz-2" ><span>2</span></li>
        <li id = "wiz-3" ><span>3</span></li>
        <li id = "wiz-4"><span>4</span></li>
        <li id = "wiz-5"><span>5</span></li>
      </ul>
    </div>

    <div class="form-wrapper">
      <%= render 'dough' %>

      <div id = "down-nav">
        <div class = "down-nav-btn">
          <%= link_to session[:back_link], class: "navbar-ac-link" do %>
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 48 48" xml:space="preserve" width="48" height="48">
            <g class="nc-icon-wrapper">
              <path id = "path1-l" fill="#72C472" d="M24,1C11.31787,1,1,11.31787,1,24s10.31787,23,23,23s23-10.31787,23-23S36.68213,1,24,1z">
              </path>
              <path id = "path2-l" fill="#FFFFFF" d="M23,16c0-0.37598-0.21094-0.72021-0.54639-0.89111c-0.33496-0.16992-0.73682-0.13867-1.04199,0.08252l-11,8 C10.15332,23.37939,10,23.68018,10,24s0.15332,0.62061,0.41162,0.80859l11,8C21.58594,32.93555,21.79248,33,22,33 c0.15479,0,0.31055-0.03613,0.45361-0.10889C22.78906,32.72021,23,32.37598,23,32v-6h13c0.55228,0,1-0.44772,1-1v-2 c0-0.55228-0.44772-1-1-1H23V16z">
              </path>
            </g>
          </svg>
          <% end %>
        </div>
        <div class = "down-nav-btn" id="submit-btn">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 48 48" xml:space="preserve" width="48" height="48">
            <g class="nc-icon-wrapper">
              <path id = "path1-r" fill="#D4D4D4" d="M24,1C11.31787,1,1,11.31787,1,24s10.31787,23,23,23s23-10.31787,23-23S36.68213,1,24,1z">
              </path>
              <path id = "path2-r" fill="#FFFFFF" d="M37.58838,23.19141l-11-8c-0.30322-0.22119-0.70703-0.25244-1.04199-0.08252 C25.21094,15.27979,25,15.62402,25,16v6H12c-0.55229,0-1,0.44772-1,1v2c0,0.55228,0.44771,1,1,1h13v6 c0,0.37598,0.21094,0.72021,0.54639,0.89111C25.68945,32.96387,25.84521,33,26,33c0.20752,0,0.41406-0.06445,0.58838-0.19141l11-8 C37.84668,24.62061,38,24.31982,38,24S37.84668,23.37939,37.58838,23.19141z">
              </path>
            </g>
          </svg>
        </div>
        <div class = "down-nav-cart">
          <p> Total: <span id = "cart"></span></p>
        </div>
      </div>
    </div>
  </div>
</section>

<% content_for(:after_js) do %>
<script>
  $(document).ready(function(){
    $('#myModal').modal('toggle');
    $("#step1").attr('class', 'hidden'); //hide submit button
    $(".radio-hide").attr('class', 'hidden'); //hide radio buttons
    //In mobile, fix navbar to the bottom of the screen
    if ($(window).width() <= 400) {
      $('#down-nav').css({
        position: "fixed", bottom: "0", right: "0", left: "0"
      });
      var bottomOfForm = $(".form-wrapper").offset().top;
      $(window).scroll(function() {
        if($(window).scrollTop() > bottomOfForm) { //scrolled past the other div?
          $('#down-nav').css({
        position: "absolute"}) //reached the desired point -- show div
        } else {
          $('#down-nav').css({
            position: "fixed", bottom: "0", right: "0", left: "0"
          })
        }
      });
    };
    $('.i-filling').click(function(){
      //Get dough id
      var doughId =  $(this).parent().attr('id');
      var split = doughId.split("fil_dough_");
      var doughIdNum = Number(split[1]);
      //Get filling id
      var fillingId = $(this).attr('id');
      var splitFill = fillingId.split("i_");
      var fillingIdNum = Number(splitFill[1]);
      //Select filling
      $(this).addClass("option-input-checked option-input-checked::before");
      //Remove selection of all other fillings
      $(".i-filling").not(this).removeClass("option-input-checked option-input-checked::before");
      //Select corresponding radio button and remove others
      $("#cake_filling_" + fillingIdNum).prop('checked', true);
      $(".filling-radio").not(this).prop('checked', false);
      //Select corresponding dough
      $("#cake_dough_" + doughIdNum).prop("checked", true);
      $("#div_" + doughIdNum).addClass("selected-card");
      //Remove color and selection from all the other doughs
      $('*[id*=div_]').not("#div_" + doughIdNum).removeClass("selected-card");
      //When choosing dough, remove color and selection from all fillings belonging to other doughs
      $("#div_" + doughIdNum + " i").removeClass("radio-circle");
      $("#div_" + doughIdNum + " i").addClass("radio-circle-color");
      //Add price to cart
      $("#cart").empty();
      $("#cart").append("<%= @doughs.first.price%>€/Kg");
      $('#path1-r').css({ fill: "#72C472" });
    });
    $("#submit-btn").click(function(e){
      if (($("*[id*=cake_dough_]").is(":checked") == true) && ($("*[id*=cake_filling_]").is(":checked") == true)) {
        $("#step1").click();
      } else {
        $(this).notify("Seleccione uma massa e um recheio");
      }
    })
  })
</script>
<% end %>

app/views/cakes/edit.html.erb
<h1>Cakes#edit</h1>
<p>Find me in app/views/cakes/edit.html.erb</p>

app/views/cakes/fillings.html.erb
<%= render "filling" %>

<% content_for(:after_js) do %>
  <script>
  $(document).ready(function(){
    $("input").change(function(){
    for (var i = 1; i < 6; i ++) {
     var radioButton = $('#cake_filling_'+ i);
     if (radioButton.prop("checked") == true){
      var id = i;
      }
    }
      $.ajax({
        url: '<%= decorations_cakes_path %>',
        type: 'GET',
        data: {'cake' : {'fillings' : id}},
        dataType: "script",
        success: function(data) {
          console.log(data);
        },
        error: function(error) {
          console.log("AJAX Error: #{error}");
        }

      })
      $("#fillings").empty();
    })
  })
  </script>
<% end %>