config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home' 

  get 'about',       to: 'pages#about'
  get 'home2',     to: 'pages#home'
  get 'gallery', to: 'pages#gallery'

  get 'design', to: 'pages#design'
  get 'contacts',     to: 'pages#contacts'

  resources :custom_cakes
  resources :contacts
  resources :subscribers, only: :create

  resources :cakes do
    collection do
      get 'doughs'
      get 'fillings'
      get 'decorations'
    end
  end

  resources :orders do
    resources :deliveries, only: [:new, :create, :confirmation]
    get 'confirmation', to: 'deliveries#confirmation'

    # ========================
    # tira tudo dos other e assign others para o index e o new/create do order_others
    resources :order_others
    member do
      get 'others'
      post 'assign_others'
    end


  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row row-height">
      <div class="col-sm-3 col-xs-6 flexbox-col">
        <%= link_to 'PASTELARIA BONJOUR', root_path %>
      </div>
      <div class="col-sm-2 col-xs-6">
        <h5>Início</h5>
        <ul>
          <li><%= link_to 'Home', root_path %></li>
          <li><a href="#">Sign up</a></li>
          <li> <%= link_to "Log in", new_user_session_path %></li>
        </ul>
      </div>
      <div class="col-sm-2 col-xs-6">
        <h5>Sobre nós</h5>
        <ul>
          <li> <%= link_to 'A Bonjour', about_path %>
          </li>
          <li>
            <%= link_to 'Contactos', contacts_path %>
          </li>
          <li> <%= link_to 'Galeria', gallery_path %>
          </li>
        </ul>
      </div>
      <div class="col-sm-2 col-xs-6">
        <h5>Encomendas</h5>
        <ul>
          <li> <%= link_to 'Encomendar', new_cake_path %>
          </li>
          <li>  <%= link_to 'Bolo personalizado', design_path %>
          </li>
          <li> <%= link_to 'Carrinho', current_order_path %>
          </li>
        </ul>
      </div>
      <div class="col-sm-3 col-xs-6 flexbox-col">
        <div class="social-networks">
          <a href="https://www.facebook.com/Pastelaria-Bonjour-Cascais-1424510534502618/"><i class="fa fa-facebook fa-2x"></i></a>
          <a href="https://www.instagram.com/pastelaria.bonjour/"><i class="fa fa-instagram fa-2x"></i></a>
          <a href="#" class="google"><i class="fa fa-google-plus fa-2x"></i></a>
        </div>
        <div class="flexbox-between">
          <%= simple_form_for @subscriber, html: { class: "form-inline"} do |f| %>
          <%= f.input :email, placeholder: "Email", label_html: {class: 'hidden'}, input_html: { class: ""}%>
          <%= f.submit "Subscrever", class: "cta-btn cta-btn-white" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-copyright text-center">
    <p> <i class="fa fa-copyright" aria-hidden="true"></i> <span>2017 Pastelaria Bonjour. Todos os direitos reservados</span> | <%= link_to "http://www.ahoy-code.com/" do %>
      Created by AhoyCode
      <% end %></p>
    </div>
  </footer>

app/views/shared/_nav.html.erb
<nav class="navbar-ac navbar-ac-fixed">
  <!-- Brand and toggle get grouped for better mobile display -->
  <%= link_to 'PASTELARIA BONJOUR', root_path, class: "navbar-ac-link" %>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="navbar-ac-right hidden-xs hidden-sm">

    <ul class="menu">
      <li>
        <%= link_to about_path, class: "navbar-ac-link" do %>
        Sobre
        <% end %>
      </li>
      <li>
        <%= link_to design_path, class: "navbar-ac-link" do %>
        Pedir Orçamento
        <% end %>
      </li>
      <li>
        <%= link_to gallery_path, class: "navbar-ac-link" do %>
        Galeria
        <% end %>
      </li>
      <li>
        <%= link_to contacts_path, class: "navbar-ac-link" do %>
        Contactos
        <% end %>
      </li>
      <li>
        <%= link_to current_order_path, class: "navbar-ac-link" do %>
        Carrinho
        <% end %>
      </li>
      <li>
        <%= link_to new_cake_path, class: "navbar-ac-button" do %>
        Encomendar
        <% end %>
      </li>
      <li>
        <% if user_signed_in? %>

        <%= link_to "Sign out", destroy_user_session_path, class: "navbar-ac-link", method: :delete %>
        <% else %>
        <%= link_to "Log in", new_user_session_path, class: "navbar-ac-button-black" %>
        <% end %>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-ac-item hidden-md hidden-lg" style = "padding: 40px 0px;">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle header-left" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-ac-dropdown-menu">
        <li>
          <%= link_to about_path do %>
          Sobre
          <% end %>
        </li>
        <li>
          <%= link_to new_cake_path do %>
          Encomendar
          <% end %>
        </li>
        <li>
          <%= link_to design_path do %>
          Pedir Orçamento
          <% end %>
        </li>
        <li>
          <%= link_to gallery_path do %>
          Galeria
          <% end %>
        </li>
        <li>
          <%= link_to contacts_path do %>
          Contactos
          <% end %>
        </li>
              <li>
        <% if user_signed_in? %>

        <%= link_to "Sign out", destroy_user_session_path%>
        <% else %>
        <%= link_to "Log in", new_user_session_path %>
        <% end %>
      </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_navbar.html.erb
<div class="navbar-ac2">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-ac-brand-2" do %>
  <%= image_tag "circle.png" %>
  <% end %>
</div>