config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home' 

  get 'about',       to: 'pages#about'
  get 'home2',     to: 'pages#home'
  get 'gallery', to: 'pages#gallery'

  get 'design', to: 'pages#design'
  get 'contacts',     to: 'pages#contacts'

  resources :custom_cakes
  resources :contacts
  resources :subscribers, only: :create

  resources :cakes do
    collection do
      get 'doughs'
      get 'fillings'
      get 'decorations'
    end
  end

  resources :orders do
    resources :deliveries, only: [:new, :create, :confirmation]
    get 'confirmation', to: 'deliveries#confirmation'

    # ========================
    # tira tudo dos other e assign others para o index e o new/create do order_others
    resources :order_others
    member do
      get 'others'
      post 'assign_others'
    end


  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  has_many :cakes, dependent: :delete_all
  has_many :order_others, dependent: :delete_all
  has_many :others, through: :order_others
  has_one :delivery, dependent: :delete
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :assign_others, :others, :show, :edit, :update, :confirmation]

  def show
    @order = Order.find(params[:id])
    @cakes = @order.cakes
    @order_others = OrderOther.where(order_id: params[:id])

    @others = @order.others
    @order_others = @order.order_others

    @others_price = @order.others.map(&:price) unless @order.others.blank?
    @others_quantity = @order.order_others.map(&:quantity) unless @order.order_others.blank?

    @cakes_total = @cakes.map(&:price).reduce(:+).to_f unless @cakes.blank?
    @others_price = @others_price.zip(@others_quantity).map{|x, y| x * y}.reduce(:+).to_f unless (@others_price.blank? || @others_quantity.blank?)

    @total = @cakes_total.to_f + @others_price.to_f
  end

  def new
    @order = Order.new
  end

  def create
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      UserMailer.purchase_confirmation(Order.find(params[:id])).deliver_now
      redirect_to confirmation_order_path(@order)
    else
      render :edit
    end
  end

  def destroy
  end

  def confirmation
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(:address, :user, :delivery_datetime, :contact_name, :contact_telephone, :contact_email)
  end

end

app/views/orders/_other.html.erb
<%= simple_form_for :order_others, url: order_order_others_path(@order), method: :post do |f| %>
<div class="form-inner-wrapper container">
  <div class="form-scroll row row-height">
    <% @others.each do |other| %>
    <div class="col-md-4 card">
      <div class = "img-decoration-wrapper" >
        <div class="row">
          <%= cl_image_tag other.photo %>
          <div class="row row-height">
            <div class="col-md-9" style = "display: flex; align-items: center;">
              <%= other.name %>
            </div>
            <div class="col-md-3" id = "other_<%= other.id %>">
              <div class="radio option-input i-other" id = "i_<%= other.id %>"></div>
            </div>
            <div class="radio-hid">
             <%= f.input :id, as: :check_boxes, collection: [other.id], label: false %>

           </div>
           <%= f.input :quantity, as: :integer, label: false %>
         </div>
         <hr>
         <div class="row">
           <div class="col-md-12">
             <p><span id= "other_price_<%= other.id %>" class = "price"><%= other.price %></span> €/un</p>
           </div>
         </div>
       </div>
     </div>
   </div>

   <% end %>
   <%= f.submit "Proximo passo", class: "btn btn-lg btn-default", id: "step3"%>
 </div>
</div>
<% end %>

app/views/orders/confirmation.html.erb
<h1>Confirmação de Encomenda</h1>

<h2>Olá <%= @order.contact_name %>, </h2>
<p>Obrigado pela tua encomenda! Por favor confirma se os dados estão correctos</p>
<p></p>
<table style="width:60%">
	<tr>
		<td><strong>Ponto Contacto</strong></td>
		<td><%= @order.contact_name %></td>
	</tr>
	<tr>
		<td><strong>Numero Contact</strong></td>
		<td><%= @order.contact_telephone%></td>
	</tr>
	<tr>
		<td><strong>Morada de Entrega</strong></td>
		<td><%= @order.address%></td>
	</tr>
	<tr>
		<td><strong>Hora de Entrega</strong></td>
		<td><%= @order.delivery_datetime%></td>
	</tr>
</table>
<p></p>
<h3><%= @order.contact_name %> Atenção:</h3> <p>Se os dados tiverem errados por favor entrem em contacto respondendo a este email</p>
<p></p>
<p>Por agora da nossa parte está tudo. Vamos por as mãos a massa (literalmente) e estaremos com vocês dia <%= @order.delivery_datetime%></p>
<p></p>

<p>Desde já obrigado,</p>
<p>Equipa Bonjour</p>

app/views/orders/new.html.erb
<div class="banner-orders">
<% unless @order.cakes.blank? %>
  <% @order.cakes.select{|cake| !cake.filling.blank? && !cake.dough.blank?}.each do |cake| %>
    <p> <%= cake.size %> <%= cake.shape %> <%= cake.dough.name %> with <%= cake.filling.name %></p>
    <p><%= link_to "Delete cake #{cake.id}", cake_path(cake), method: :delete %></p>
  <% end %>
  <%= link_to 'Still hungry!', new_cake_path %>
  <%= link_to 'Pay now', new_order_payment_path(@order) %>

<% else %>
  <%= link_to 'Order a wonderfull cake!', new_cake_path %>
<% end %>
</div>

<section class="form-page">
  <div class="container" >
    <h1 id = "step-title">Carrinho</h1>
    <div id="progresstracker">
      <ul>
        <li id = "wiz-1" class = "" ><span>1</span></li>
        <li id = "wiz-2" class = ""><span>2</span></li>
        <li id = "wiz-3" class = "><span>3</span></li>
        <li id = "wiz-4" class = ""><span>4</span></li>
        <li id = "wiz-4"><span>5</span></li>
      </ul>
    </div>

    <div class="form-wrapper" style = "overflow: scroll;">
      <div class="form-inner-wrapper">
        <div class="form-scroll">
          <h4>O seu carrinho está vazio</h4>

      </div>
    </div>
      <div id = "down-nav">
        <div class = "down-nav-btn">
          <%= link_to session[:back_link], class: "navbar-ac-link" do %>
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 48 48" xml:space="preserve" width="48" height="48">
            <g class="nc-icon-wrapper">
              <path id = "path1-l" fill="#72C472" d="M24,1C11.31787,1,1,11.31787,1,24s10.31787,23,23,23s23-10.31787,23-23S36.68213,1,24,1z">
              </path>
              <path id = "path2-l" fill="#FFFFFF" d="M23,16c0-0.37598-0.21094-0.72021-0.54639-0.89111c-0.33496-0.16992-0.73682-0.13867-1.04199,0.08252l-11,8 C10.15332,23.37939,10,23.68018,10,24s0.15332,0.62061,0.41162,0.80859l11,8C21.58594,32.93555,21.79248,33,22,33 c0.15479,0,0.31055-0.03613,0.45361-0.10889C22.78906,32.72021,23,32.37598,23,32v-6h13c0.55228,0,1-0.44772,1-1v-2 c0-0.55228-0.44772-1-1-1H23V16z">
              </path>
            </g>
          </svg>
          <% end %>
        </div>
        <div class = "down-nav-btn" id="submit-btn">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 48 48" xml:space="preserve" width="48" height="48">
            <g class="nc-icon-wrapper">
              <path id = "path1-r" fill="#D4D4D4" d="M24,1C11.31787,1,1,11.31787,1,24s10.31787,23,23,23s23-10.31787,23-23S36.68213,1,24,1z">
              </path>
              <path id = "path2-r" fill="#FFFFFF" d="M37.58838,23.19141l-11-8c-0.30322-0.22119-0.70703-0.25244-1.04199-0.08252 C25.21094,15.27979,25,15.62402,25,16v6H12c-0.55229,0-1,0.44772-1,1v2c0,0.55228,0.44771,1,1,1h13v6 c0,0.37598,0.21094,0.72021,0.54639,0.89111C25.68945,32.96387,25.84521,33,26,33c0.20752,0,0.41406-0.06445,0.58838-0.19141l11-8 C37.84668,24.62061,38,24.31982,38,24S37.84668,23.37939,37.58838,23.19141z">
              </path>
            </g>
          </svg>
        </div>
        <div class = "down-nav-cart">
          <p> Total: <span id = "cart"></span></p>
        </div>
      </div>
   <div id = "btn1" class = "button">
  <%= image_tag "cake-13.svg" %>
  <%= link_to 'Adicionar bolo', new_cake_path %>
  </div>
 </div>
</div>
</section>

app/views/orders/others.html.erb
<div class="form-page" style = "padding-bottom: 100px; padding-top: 100px;">
  <div class="container">
    <h1 id = "step-title" style = "font-size: 30px;">Adicione extras</h1>
    <div id="progresstracker">
      <ul>
        <li class="complete"><span>1</span></li>
        <li class="complete"><span>2</span></li>
        <li class="active complete"><span>3</span></li>
        <li><span>4</span></li>
      </ul>
    </div>

    <div class="form-wrapper">
      <%= render "other" %>
      <div id = "down-nav">
        <div class = "down-nav-btn">
          <%= link_to session[:back_link], class: "navbar-ac-link" do %>
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 48 48" xml:space="preserve" width="48" height="48">
            <g class="nc-icon-wrapper">
              <path id = "path1-l" fill="#72C472" d="M24,1C11.31787,1,1,11.31787,1,24s10.31787,23,23,23s23-10.31787,23-23S36.68213,1,24,1z">
              </path>
              <path id = "path2-l" fill="#FFFFFF" d="M23,16c0-0.37598-0.21094-0.72021-0.54639-0.89111c-0.33496-0.16992-0.73682-0.13867-1.04199,0.08252l-11,8 C10.15332,23.37939,10,23.68018,10,24s0.15332,0.62061,0.41162,0.80859l11,8C21.58594,32.93555,21.79248,33,22,33 c0.15479,0,0.31055-0.03613,0.45361-0.10889C22.78906,32.72021,23,32.37598,23,32v-6h13c0.55228,0,1-0.44772,1-1v-2 c0-0.55228-0.44772-1-1-1H23V16z">
              </path>
            </g>
          </svg>
          <% end %>
        </div>
        <div class = "down-nav-btn" id="submit-btn">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 48 48" xml:space="preserve" width="48" height="48">
            <g class="nc-icon-wrapper">
              <path id = "path1-r" fill="#D4D4D4" d="M24,1C11.31787,1,1,11.31787,1,24s10.31787,23,23,23s23-10.31787,23-23S36.68213,1,24,1z">
              </path>
              <path id = "path2-r" fill="#FFFFFF" d="M37.58838,23.19141l-11-8c-0.30322-0.22119-0.70703-0.25244-1.04199-0.08252 C25.21094,15.27979,25,15.62402,25,16v6H12c-0.55229,0-1,0.44772-1,1v2c0,0.55228,0.44771,1,1,1h13v6 c0,0.37598,0.21094,0.72021,0.54639,0.89111C25.68945,32.96387,25.84521,33,26,33c0.20752,0,0.41406-0.06445,0.58838-0.19141l11-8 C37.84668,24.62061,38,24.31982,38,24S37.84668,23.37939,37.58838,23.19141z">
              </path>
            </g>
          </svg>
        </div>
        <div class = "down-nav-cart">
          <p> Total: <span id = "cart"></span></p>
        </div>
      </div>
    </div>
  </div>
</div>


<% content_for(:after_js) do %>
<script>
  $(document).ready(function(){
    $("#step3").attr('class', 'hidden'); //hide submit button
    //$(".radio-hide").attr('class', 'hidden'); //hide radio buttons
    $(".radio-hide").attr('class', 'hidden'); //hide radio buttons
    $("#submit-btn").removeClass("hidden");
    $("#cart").append("<%= @total %>")
    //In mobile, fix navbar to the bottom of the screen
    if ($(window).width() <= 400) {
      $('#down-nav').css({
        position: "fixed", bottom: "0", right: "0", left: "0"
      });
      var bottomOfForm = $(".form-wrapper").offset().top;
      $(window).scroll(function() {
        if($(window).scrollTop() > bottomOfForm) { //scrolled past the other div?
          $('#down-nav').css({
        position: "absolute"}) //reached the desired point -- show div
        } else {
          $('#down-nav').css({
            position: "fixed", bottom: "0", right: "0", left: "0"
          })
        }
      });
    };
    $('.i-other').click(function(){
      //Get other id
      var otherId =  $(this).attr('id');
      var split = otherId.split("i_");
      var otherIdNum = Number(split[1]);
      //Get current quantity
      var otherQuantity = Number($("#other_quantity_" + otherIdNum).text());
      //Get other price
      var otherPrice = Number($("#other_price_" + otherIdNum).text());
      //Get cart's current price
      var cartPrice = Number($("#cart").text());
      if ($(this).hasClass("option-input-checked")) { //If it is already selected
        //Unselect radio
        $(this).removeClass("option-input-checked option-input-checked::before");
        //Unselect input
        $("#other_id_" + otherIdNum).prop('checked', false);
        //Remove price from cart
        $("#cart").html((cartPrice - otherPrice * otherQuantity).toFixed(2));
        //Reset quantity
        $("#other_quantity_" + otherIdNum).html("0")
      } else {
        //Select other
        $(this).addClass("option-input-checked option-input-checked::before");
        //Select corresponding checkbox
        $("#other_id_" + otherIdNum).prop('checked', true);
        // Add other's price
        $("#cart").html((cartPrice + otherPrice).toFixed(2));
        //Add 1 unit
        $("#other_quantity_" + otherIdNum).html("1")
        }
    });

    $(".plus").click(function(){
      //Get other id
      var otherId =  $(this).attr('id');
      var split = otherId.split("plus_");
      var otherIdNum = Number(split[1]);
      //Get current quantity
      var otherQuantity = Number($("#other_quantity_" + otherIdNum).text());
      //Get other price
      var otherPrice = Number($("#other_price_" + otherIdNum).text());
      //Get cart's current price
      var cartPrice = Number($("#cart").text());
      //Select radio
      $("#i_" + otherIdNum).addClass("option-input-checked option-input-checked::before");
      //Select corresponding checkbox
      $("#other_id_" + otherIdNum).prop('checked', true);
      //Increase quantity
      $("#other_quantity_" + otherIdNum).html(otherQuantity + 1);
      // Add other's price
      $("#cart").html((cartPrice + otherPrice).toFixed(2));
    });

      $(".minus").click(function(){
      //Get other id
      var otherId =  $(this).attr('id');
      var split = otherId.split("minus_");
      var otherIdNum = Number(split[1]);
      //Get current quantity
      var otherQuantity = Number($("#other_quantity_" + otherIdNum).text());
      //Get other price
      var otherPrice = Number($("#other_price_" + otherIdNum).text());
      //Get cart's current price
      var cartPrice = Number($("#cart").text());
      if (otherQuantity > 1) {
      //Decrease quantity
      $("#other_quantity_" + otherIdNum).html(otherQuantity - 1);
      // Remove other's price
      $("#cart").html((cartPrice - otherPrice).toFixed(2));
      } else if (otherQuantity === 1) {
      //Decrease quantity
      $("#other_quantity_" + otherIdNum).html(otherQuantity - 1);
      //Unselect radio
      $("#i_" + otherIdNum).removeClass("option-input-checked option-input-checked::before");
      //Unselect corresponding checkbox
      $("#other_id_" + otherIdNum).prop('checked', false);
      // Remove other's price
      $("#cart").html((cartPrice - otherPrice).toFixed(2));
      } else {

      }
    })

    $("#submit-btn").click(function(e){
     $("#step3").click();
    // }
  })
  })
</script>
<% end %>

app/views/orders/show.html.erb
<section class="form-page">
  <div class="container" >
    <h1 id = "step-title">Carrinho</h1>
    <div id="progresstracker">
      <ul>
        <li id = "wiz-1" class = "complete" ><span>1</span></li>
        <li id = "wiz-2" class = "complete"><span>2</span></li>
        <li id = "wiz-3" class = "complete"><span>3</span></li>
        <li id = "wiz-4" class = "complete active"><span>4</span></li>
        <li id = "wiz-4"><span>5</span></li>
      </ul>
    </div>

    <div class="form-wrapper" style = "overflow: scroll;">
      <div class="form-inner-wrapper">
        <div class="form-scroll">
          <div class="row">
            <div class="col-md-12">
              <% unless @order.cakes.blank? %>
              <% @order.cakes.select{|cake| !cake.filling.blank? && !cake.dough.blank?}.each do |cake| %>
              <div id = "cake_<%=cake.id%>">
                <div class="row card">
                  <div class="col-md-2 flexbox">
                    <%= cl_image_tag cake.dough.photo %>
                  </div>
                  <div class="col-md-10">
                    <div class = "flexbox-between">
                      <div>
                        <p>Bolo de <%= cake.dough.name %> com <%= cake.filling.name %> </p>
                        <p class = "text-09"><%= cake.size %>Kg</p>
                        <hr>
                        <%= link_to "Apagar", cake_path(cake), class: "delete-link", id: "cake_delete_#{cake.id}", method: :delete, remote: :true %>
                      </div>
                      <p class = "text-09"><%= cake.price %>€</p>
                    </div>

                  </div>
                </div>
              </div>
              <% end %>
              <% end %>
              <% unless @order.others.blank? %>
              <% @order.order_others.each do |order_other| %>
              <div id = "other_<%=order_other.id%>">
                <div class="row card">
                  <div class="col-md-2">
                    <%= cl_image_tag order_other.other.photo %>
                  </div>
                  <div class="col-md-10">
                    <div style = "display: flex; justify-content: space-between;">
                      <div>
                        <p><%= order_other.other.name %></p>
                        <hr>
                     </div>
                     <p class = "text-09"><%= order_other.quantity %>un</p>
                     <% @subtotal = order_other.quantity * order_other.other.price%>
                     <p class = "text-09"><%= @subtotal %>€</p>
                   </div>
                   <%= link_to "Apagar", order_order_other_path(@order, order_other), class: "delete-link", id: "other_delete_#{order_other.id}", method: :delete, remote: :true %>
                 </div>
               </div>
             </div>
             <% end %>
             <% end %>
           </div>
           <div class="col-md-6">
            <%= link_to "", new_order_delivery_path(@order), id: "delivery" %>
          </div>
        </div>
      </div>
    </div>
      <div id = "down-nav">
        <div class = "down-nav-btn">
          <%= link_to session[:back_link], class: "navbar-ac-link" do %>
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 48 48" xml:space="preserve" width="48" height="48">
            <g class="nc-icon-wrapper">
              <path id = "path1-l" fill="#72C472" d="M24,1C11.31787,1,1,11.31787,1,24s10.31787,23,23,23s23-10.31787,23-23S36.68213,1,24,1z">
              </path>
              <path id = "path2-l" fill="#FFFFFF" d="M23,16c0-0.37598-0.21094-0.72021-0.54639-0.89111c-0.33496-0.16992-0.73682-0.13867-1.04199,0.08252l-11,8 C10.15332,23.37939,10,23.68018,10,24s0.15332,0.62061,0.41162,0.80859l11,8C21.58594,32.93555,21.79248,33,22,33 c0.15479,0,0.31055-0.03613,0.45361-0.10889C22.78906,32.72021,23,32.37598,23,32v-6h13c0.55228,0,1-0.44772,1-1v-2 c0-0.55228-0.44772-1-1-1H23V16z">
              </path>
            </g>
          </svg>
          <% end %>
        </div>
        <div class = "down-nav-btn" id="submit-btn">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 48 48" xml:space="preserve" width="48" height="48">
            <g class="nc-icon-wrapper">
              <path id = "path1-r" fill="#72C472" d="M24,1C11.31787,1,1,11.31787,1,24s10.31787,23,23,23s23-10.31787,23-23S36.68213,1,24,1z">
              </path>
              <path id = "path2-r" fill="#FFFFFF" d="M37.58838,23.19141l-11-8c-0.30322-0.22119-0.70703-0.25244-1.04199-0.08252 C25.21094,15.27979,25,15.62402,25,16v6H12c-0.55229,0-1,0.44772-1,1v2c0,0.55228,0.44771,1,1,1h13v6 c0,0.37598,0.21094,0.72021,0.54639,0.89111C25.68945,32.96387,25.84521,33,26,33c0.20752,0,0.41406-0.06445,0.58838-0.19141l11-8 C37.84668,24.62061,38,24.31982,38,24S37.84668,23.37939,37.58838,23.19141z">
              </path>
            </g>
          </svg>
        </div>
        <div class = "down-nav-cart">
          <p> Total: <span id = "cart"></span></p>
        </div>
      </div>

<div id = "btn1" class = "button">
  <%= image_tag "cake-13.svg" %>
  <%= link_to 'Adicionar bolo', new_cake_path %>
  </div>
<div id = "btn2" class = "button">
  <%= image_tag "muffin.svg" %>
  <%= link_to 'Adicionar extras', order_order_others_path(@order) %>

  </div>


 </div>
 <%= link_to design_path, class: "navbar-ac-link" do %>
 Não encontra o que quer?
 <% end %>
</div>
</section>

<% content_for(:after_js) do %>
<script>
  $(document).ready(function(){
    $("#delivery").addClass("hidden");
    //In mobile, fix navbar to the bottom of the screen
    if ($(window).width() <= 400) {
      $('#down-nav').css({
        position: "fixed", bottom: "0", right: "0", left: "0"
      });
      var bottomOfForm = $(".form-wrapper").offset().top;
      $(window).scroll(function() {
        if($(window).scrollTop() > bottomOfForm) { //scrolled past the other div?
          $('#down-nav').css({
        position: "absolute"}) //reached the desired point
        } else {
          $('#down-nav').css({
            position: "fixed", bottom: "0", right: "0", left: "0"
          });
        }
      });
    };
    //Delete cake
    $("*[id*=cake_delete_]").click(function(){
     var btnId = $(this).attr("id");
     var split = btnId.split("cake_delete_");
     var cakeId = "#cake_" + split[1];
     $(cakeId).remove();
     $(this).remove();

   })
    //Delete Other
    $("*[id*=other_delete_]").click(function(){
     var btnId = $(this).attr("id");
     var split = btnId.split("other_delete_");
     var otherId = "#other_" + split[1];
     $(otherId).remove();
     $(this).remove();
   })

    //Add price to cart
    $("#cart").append("<%= @total %>€");
//Submit
$("#submit-btn").click(function(e){
  $("#delivery")[0].click();
});
})
</script>
<% end %>